#!/usr/bin/env bash
curl -F "version=4" \
	-F 'note={"r":"2014-04-10 01:02:03","l":"35.05","n":"-119.95","a":"1345","s":"0","h":"","v":"","t":"11","d":"Test image note","i":"test-all-the-things"}' \
	-F "device=01234567890123456789012345678901" \
	-F "file=@test-all-the-things.jpg" \
	-v \
	$1


